### ISSUE TITLE
add black pre-commit hook

### ISSUE THREAD

**Issue by rbturnbull** [jjmccollum/teiphy#6]

**Comment by jjmccollum** [comment]
@rbturnbull I wanted to reopen this for a moment because the pre-commit hook isn't working for me. I have Python 3.10 installed on my machine, so the line `language_version: python3.8` in `.pre-commit-config.yaml` is throwing an error when I try to commit changes. Do we need to specify a particular `language_version` here, or can this line be removed from the config file?

**Comment by jjmccollum** [comment]
(Also, based on what I'm seeing on Stack Overflow related to this issue, the GitHub repo URL in the config file should be updated from `https://github.com/ambv/black` to `https://github.com/psf/black`.)

Everything worked for me once I removed the `language_version: python3.8` line (this change was in my most recent commit), so if that looks fine to you, then we can re-close this issue.
